# Generated by Django 3.0.3 on 2020-08-21 07:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('esapp', '0002_producer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('price', models.FloatField(null=True)),
                ('info', models.TextField(blank=True, max_length=800, null=True)),
                ('category', models.CharField(choices=[('上衣', '上衣'), ('下著', '下著'), ('內衣褲', '內衣褲'), ('外套', '外套'), ('帽子', '帽子'), ('襪子', '襪子'), ('鞋子', '鞋子'), ('手/袖套', '手/袖套'), ('涼感小物', '涼感小物'), ('泳裝', '泳裝'), ('毛巾', '毛巾'), ('護具', '護具'), ('運動器材', '運動器材'), ('登山用品', '登山用品'), ('機車配件', '機車配件'), ('其他', '其他')], default='其他', max_length=200, null=True)),
                ('discount', models.FloatField(default=1.0, max_length=10, null=True)),
                ('note', models.TextField(blank=True, max_length=500, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('image', models.ImageField(blank=True, default='default.png', null=True, upload_to='')),
                ('producer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='esapp.Producer')),
            ],
        ),
        migrations.CreateModel(
            name='Size',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Trail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, null=True)),
                ('address', models.CharField(max_length=200, null=True)),
                ('gmap', models.CharField(max_length=500, null=True)),
                ('length', models.CharField(max_length=50, null=True)),
                ('once_time', models.CharField(max_length=50, null=True)),
                ('pic_ref1', models.CharField(max_length=500, null=True)),
                ('pic_ref2', models.CharField(blank=True, max_length=500, null=True)),
                ('info', models.TextField(blank=True, max_length=800, null=True)),
                ('source', models.CharField(max_length=500, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProductSet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='esapp.Color')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='esapp.Product')),
                ('size', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='esapp.Size')),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='tag',
            field=models.ManyToManyField(to='esapp.Tag'),
        ),
    ]
