# Generated by Django 3.0.3 on 2020-08-26 17:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('esapp', '0004_remove_friend_member'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='discount',
        ),
    ]
