# Generated by Django 3.0.3 on 2020-08-27 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('esapp', '0007_auto_20200827_0331'),
    ]

    operations = [
        migrations.AlterField(
            model_name='friend',
            name='phone',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='producer',
            name='producer_phone',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='producer',
            name='producer_time',
            field=models.CharField(blank=True, default='0900-1800', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='info',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='note',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
    ]
