# Generated by Django 3.0.3 on 2020-09-11 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('esapp', '0010_auto_20200911_1251'),
    ]

    operations = [
        migrations.AlterField(
            model_name='friend',
            name='phone',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True),
        ),
    ]
